name: Odds Checker

# Se ejecuta cada 30 minutos y se puede lanzar manualmente
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configurar Java 17 y cache de Maven
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      # 3️⃣ Build con Maven (descarga dependencias y compila)
      - name: Build project
        run: mvn clean compile

      # 4️⃣ Ejecutar la clase Prueba con Maven exec
      - name: Run Odds Checker
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: mvn exec:java -Dexec.mainClass="Prueba"
